using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using new_Karlshop.Models;
using Microsoft.Extensions.Configuration;
using new_Karlshop.Models.AccountViewModels;
using System.Net;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using System.Security.Claims;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;
using System.Text;

namespace new_Karlshop.Controllers
{
    //[Produces("application/json")]
   // [Route("api/TokenAPI")]
    //public class TokenAPIController : Controller
    //{
    //}

    [Route("[controller]/[action]")]
    public class TokenAPI : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IConfiguration _configuration;

        // Constructor.
        public TokenAPI(
                UserManager<ApplicationUser> userManager,
                SignInManager<ApplicationUser> signInManager,
                IConfiguration configuration
            )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _configuration = configuration;
        }

        // Generates a fake collection for demonstration purposes. 
        public List<LoginViewModel> GetFakeData()
        {
            List<LoginViewModel> logins = new List<LoginViewModel>();
            logins.Add(new LoginViewModel()
            {
                Email = "bob@home.com",
                Password = "password"
            });
            logins.Add(new LoginViewModel()
            {
                Email = "fakeuser@home.com",
                Password = "password"
            });
            return logins;
        }

        // This Action method does not require authentication.
        [HttpGet]
        public IEnumerable<LoginViewModel> Public()
        {
            return GetFakeData();
        }

        // This Action method requires authentication.
        [HttpGet]
        // Since we have cookie authentication and Jwt authentication we must
        // specify that we want Jwt authentication here.
        [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
        public IEnumerable<LoginViewModel> Protected()
        {
            return GetFakeData();
        }

        // This Action method enables web api login but with the Identity framework
        // that was added when the project was generated by the wizard.
        [HttpPost]
        public async Task<object> Login([FromBody] LoginVM model)
        {
            var result = await _signInManager.PasswordSignInAsync(
                                model.Email, model.Password, false, false);
            if (result.Succeeded)
            {
                var appUser = _userManager.Users.SingleOrDefault(r =>
                                            r.Email == model.Email);
                return await GenerateJwtToken(model.Email, appUser);
            }
            throw new ApplicationException("INVALID_LOGIN_ATTEMPT");
        }

        // This Action method lets us register new users with the Identity framework.
        [HttpPost]
        public async Task<object> Register([FromBody] RegisterVM model)
        {
            var user = new ApplicationUser
            {
                UserName = model.Email,
                Email = model.Email
            };
            var result = await _userManager.CreateAsync(user, model.Password);

            if (result.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);
                return await GenerateJwtToken(model.Email, user);
            }
            throw new ApplicationException("UNKNOWN_ERROR");
        }

        // Generates a token using settings stored in the appsettings.json file.
        private async Task<object> GenerateJwtToken(string email,
                                                    IdentityUser user)
        {
            var claims = new List<Claim> {
            new Claim(JwtRegisteredClaimNames.Sub, email),
            new Claim(JwtRegisteredClaimNames.Jti,
                        Guid.NewGuid().ToString()),
            new Claim(ClaimTypes.NameIdentifier, user.Id)
        };

            var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(
                            _configuration["TokenInformation:Key"]));
            var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

            var expires = DateTime.Now.AddDays(Convert.ToDouble(1));
            var token = new JwtSecurityToken(
                _configuration["TokenInformation:Issuer"],
                _configuration["TokenInformation:Audience"],
                claims,
                expires: expires,
                signingCredentials: creds
            );
            var formattedToken = new JwtSecurityTokenHandler().WriteToken(token);
            return Ok(new { token = formattedToken });
        }

        // It would be better to put this class in a ViewModels folder.
        public class LoginVM
        {
            [Required]
            public string Email { get; set; }

            [Required]
            public string Password { get; set; }
        }

        // It would be better to put this class in a ViewModels folder.
        public class RegisterVM
        {
            [Required]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "PASSWORD_MIN_LENGTH", MinimumLength = 6)]
            public string Password { get; set; }
        }
    }



}